# Generated by Django 3.2.5 on 2021-08-10 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('meta_trait_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('accession', models.CharField(max_length=50)),
                ('trait', models.CharField(max_length=50)),
                ('biological_replicate', models.CharField(max_length=4)),
                ('technical_replicate', models.CharField(max_length=4)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=1000, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('trait_id', models.CharField(max_length=50, unique=True)),
                ('trait_name', models.CharField(max_length=50)),
                ('method_id', models.CharField(max_length=50)),
                ('method_name', models.CharField(max_length=50)),
                ('method_description', models.CharField(max_length=50)),
                ('scale_id', models.CharField(max_length=50)),
                ('scale_name', models.CharField(max_length=50)),
                ('scale_ll', models.CharField(max_length=50)),
                ('scale_ul', models.CharField(max_length=50)),
                ('method_ref', models.CharField(max_length=50)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('study_id', models.CharField(max_length=100, unique=True)),
                ('meta_trait', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description_experimental_design', models.CharField(max_length=500)),
                ('growth_facility', models.CharField(blank=True, choices=[('field', 'Field'), ('greenhouse', 'Green House'), ('culture_room', 'Culture Room'), ('phytotron', 'Phytotron')], max_length=20, null=True)),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=6)),
                ('light_intensity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('relative_humidity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('other_conditions', models.CharField(max_length=100)),
                ('treatment_type', models.CharField(blank=True, choices=[('biotic', 'Biotic'), ('abiotic', 'Abiotic'), ('other', 'Other')], max_length=10, null=True)),
                ('treatment_description', models.CharField(blank=True, max_length=150, null=True)),
                ('treatment_name', models.CharField(max_length=50)),
                ('treatment_value', models.CharField(max_length=50)),
                ('treatment_developmental_stage', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('phenotypic', 'Phenotype'), ('genotypic', 'Genotypic')], default='phenotypic', max_length=20)),
                ('observation_developmental_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('tissue', models.CharField(max_length=100)),
                ('biological_replicates', models.IntegerField()),
                ('technical_replicates', models.IntegerField()),
                ('trait_name', models.CharField(max_length=100)),
                ('meta_trait_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='file_upload.metatrait')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='file_upload.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='metatrait',
            name='traits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file_upload.trait'),
        ),
    ]
